### ISSUE TITLE
w3c validation error 

### ISSUE THREAD

**Issue by tsgit** [inspirehep/inspire#137]
w3c validator complains that the mandatory type attribute is missing in the style element

``` javascript
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 376)  <style>
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 377)    @media print {
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 378)     a[href]:after {
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 379)     content: none !important;
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 380)     }
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 381)    }
ebf14555 (Eamonn Maguire        2015-11-09 15:28:05 +0100 382)  </style>
```

Always check validator when changing HTML source!

https://validator.w3.org/check?uri=http%3A%2F%2Finspirehep.net%2F&charset=%28detect+automatically%29&doctype=Inline&ss=1&group=0&verbose=1&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

The attribute given above is required for an element that you've used, but you have omitted it. For instance, in most HTML and XHTML document types the "type" attribute is required on the "script" element and the "alt" attribute is required for the "img" element.

**Comment by jmartinm** [comment]
I personally have never seen a `type` attribute in a style tag. If it is mandatory, W3 does not do a very good job in their documentation http://www.w3schools.com/tags/tag_style.asp

**Comment by jmartinm** [comment]
Also http://www.w3schools.com/tags/att_style_type.asp

> In HTML5, the type attribute is no longer required for CSS. The default value is "text/css".

It's the same for `<script>` tag. In HTML5 `type` is not required.

**Comment by tsgit** [comment]
Hi Javier, 

thanks for responding.

Sure, it's a harmless omission and doesn't apply for HTML5 any longer.

However I happened to alter HTML yesterday and wanted to verify my changes and this *harmless* problem might obscure actual problems and we should strive to validate. This is more about procedure and attention to detail than a missing style attribute. I agree that many of the example snippets on the web are sloppy about this, though the normative spec is unambiguous

prod pages declare to be XHTML-1.0-Transitional 

http://www.w3.org/TR/xhtml1/dtds.html#a_dtd_XHTML-1.0-Transitional


<!ELEMENT style (#PCDATA)>
<!ATTLIST style
  %i18n;
  id          ID             #IMPLIED
  type        %ContentType;  #REQUIRED
  media       %MediaDesc;    #IMPLIED
  title       %Text;         #IMPLIED
  xml:space   (preserve)     #FIXED 'preserve'
  >

the older
http://www.w3.org/TR/html4/present/styles.html
outlines some ways to declare the default type in meta tags or headers

Cheers
T.

**Comment by tsgit** [comment]
https://github.com/inspirehep/inspire/pull/243
