### ISSUE TITLE
Institutions: double longitude instead of latitude/longitude

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#170]
Roughly 1% of the institutions have two longitudes instead of a latitude/longitude pair: https://inspirehep.net/search?ln=en&cc=Institutions&ln=en&cc=Institutions&p=034__d%3A%2F.*%2F+and+not+034__f%3A%2F.*%2F&action_search=Search&sf=institutionname&so=a&rm=&rg=25&sc=0&of=hb

This could belong to Asana (which is why I'm pinging @annetteholtkamp), but I think that a solution could be built using a script that calls a geocoding service (which is why I'm pinging @kaplun).

**Comment by kaplun** [comment]
Yep, that would be indeed great to tackle, especially in view of loading all record onto QA. I might look into it on Monday, unless anyone volunteers for implementing a script that takes a list of addresses and feed them (slowly) to Google to obtain geocoding.

**Comment by kaplun** [comment]
@inspirehep/inspire-dir how were this numbers captured in the first place?

We were thinking of writing an easy tool to correct/fill all these numbers based on Google API. Google results offer the possibility to also return the rectangle where an institute is included and this could be used to double check that proposed modifications are consistent or totally on a different place.

**Comment by eamonnmag** [comment]
You don't need to use Google. As shown before, this API does it using whatever endpoint you want, and some have no access limits at all - https://pypi.python.org/pypi/geopy

**Comment by kaplun** [comment]
Thanks, I have missed this information. Nice API. Now this open up the question of which provider is the best. I assume OpenStreet map will be great in certain countries but not all.

Also to cross check the data we have so far, I guess we can use the available distance function to verify that the coordinate we have are within a ray of e.g. 10KMs

**Comment by eamonnmag** [comment]
openstreet map is pretty cool. Take some of the more obscure addresses alongside some common ones and see how it does. It doesn't need to be exact, just good enough :)

**Comment by aw-bib** [comment]
To my limited experience openstreetmap beats google hands down in the parts of Europe I travelled (even in the more obscure backyards), while it seemed that the US is still Google country. Probably, it is an option to use whatever is best?

**Comment by jacquerie** [comment]
Here it is on Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601659/
