### ISSUE TITLE
Institutions: remove non-numerical values from 510__0

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#178]
The records returned by this query: https://inspirehep.net/search?ln=en&cc=Institutions&ln=en&cc=Institutions&p=510__0%3A%2F%5B%5E0-9%5D%2F&action_search=Search&sf=institutionname&so=a&rm=&rg=25&sc=0&of=hb have non-numerical values in the `510__0` field. I think those values should be removed, since they provide no value and would just complicate my DoJSON rules.

Since they are just a few, this is probably better handled by manual curation.

**Comment by kaplun** [comment]
I fixed them now.
