### ISSUE TITLE
Journals: do we allow 4/5 letter CODENs?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#198]
Yet another more of a question than an issue. The following query returns all Journals with a 4 or 5 letter CODEN: https://inspirehep.net/search?ln=en&cc=Journals&ln=en&cc=Journals&p=030__a%3A%2F%5E%28%5Cd%7B4%7D%7C%5Cd%7B5%7D%29%24%2F&action_search=Search&sf=&so=d&rm=&rg=25&sc=0&of=hb (in particular, there's only one record with a four letter CODEN: https://inspirehep.net/record/1212112/export/xm).

Are those okay? ~~We are currently asserting in the schema that a CODEN has exactly 6 characters, but maybe 4/5 are okay too~~.

**Comment by jacquerie** [comment]
Whoops, I was wrong in my previous post. The errors (https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601671/events/) were due to the fact that `\w` doesn't match a dash (https://docs.python.org/2/library/re.html#regular-expression-syntax).

So the only question is for lone 4-letter CODEN.

**Comment by aw-bib** [comment]
As a bibliographic side note: the official CODEN is **6** alphanumeric characters. The authoritative source would be [CASSI](http://cassi.cas.org/search.jsp) However, I fear this is a closed database that could not easily be used to brush up our local information.
