### ISSUE TITLE
Jobs Hidden: how many continents are there in the world?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#199]
Cheeky title, serious question. This is the current state of the `043__a` field in INSPIRE Jobs:
```
   1 Europe / South America
   1 Europe, North America
   1 North Americsa
   1 Noth America
   2 Asia, North America
   2 United States
   5 eu
   7 na
  14 Choose one
  24 AF
  70 Middle East
  88 Africa
 140 Australasia
 162 South America
 213 Australia
 715 Asia
4009 North America
4554 Europe
```

Let's say that we assume the 7 continent model.

1. Shall `continent` be an array, so that I can accomodate all the records with a `/`?
2. What about `Middle East`? Is it too contentious to just use `Asia` for it?

**Comment by tsgit** [comment]
from the user's perspective I think geopolitical and cultural regions are more important for job search than continents. I think when looking for a job Middle East and e.g. India is a huge  difference. Also EU is useful in terms of work permits and visa situation, etc. So can we rephrase this question and ask if the label continent is appropriate for this field?

**Comment by jacquerie** [comment]
These are all good points. Maybe we should call it `region`, and define a taxonomy (in the end, an `enum`) which more closely expresses "geopolitical and cultural regions"?

**Comment by hoc3426** [comment]
Let's stick with "region" as given by:
 70 Middle East
  88 Africa
 140 Australasia
 162 South America
 213 Australia
 715 Asia
4009 North America
4554 Europe

There shouldn't be "/" or "," if there's more than one (say a joint appointment between Fermilab and CERN) there would be two instances of "region".

I've cleaned up the things that didn't fit in this.

**Comment by jacquerie** [comment]
Solution pushed at https://github.com/inspirehep/inspire-next/pull/1406. @hoc3426, may I ask why Australia and Australasia should be two different regions? That's what I did in my PR, but it's the only thing that perplexes me...

**Comment by hoc3426** [comment]
Wow, I missed that. No, it should all be Australasia.
