### ISSUE TITLE
Cv format commenting improvements

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire#213]
My beloved wife reports that it's currently technically difficult to remove comments from our LaTeX output formats. E.g.:

https://inspirehep.net/search?ln=it&ln=it&p=storaci&of=tlcv&action_search=Cerca&sf=earliestdate&so=d&rm=&rg=25&sc=0

E.g. one would need to use regular expression in order to automatically strip away % in front of lines such as:

`%2 citations counted in INSPIRE as of 24 Aug 2016`

or

`%(Aug 23, 2016)`

Not all editor supports it and not all users master regexp.

One possible quick solution is e.g. to add a constant improbable suffix after the percentage char, so that even dummy editors can search and replace them.

E.g. 
- `%-- 2 citations counted in INSPIRE as of 24 Aug 2016`
- `%== (Aug 23, 2016)`

**Comment by kaplun** [comment]
cc: @tsgit

**Comment by kaplun** [comment]
Alternatively one can protect these lines using LaTeX macros that can be toggled at the beginning of the produced output so that the user can just set a flag in order to display/hide each particular line.

**Comment by tsgit** [comment]
the macros are a neat solution, but the cynic in me would say that users smart enough to understand and use the function of those macros would likely also know regexp well. 

The CV format is one of several formats that should be generated with more flexibility from a common metaformat which I understand CSL will provide (minus the up-to-date citation count)

as for macros, something like this (untested)

\newif\ifcitationcount
\citationcountfalse
% \citationcounttrue
\newcommand{\showcitationcount}[1]{\ifcitationcount {#1} \fi}

\begin{document}
.....

\showcitationcount{2 citations counted in INSPIRE as of 24 Aug 2016}


mmh, looks quite complex  and there need to be different macros for different comments and users are supposed to understand how to manipulate the preamble?

**Comment by tsgit** [comment]
@kaplun 
so maybe the simple unique prefix method suggested is preferable. What does Barbara think?

**Comment by kaplun** [comment]
@tsgit yup that would be perfect. Basically only one change to safely amend 300 publication and toggle their display.

The issue with CSL (if I am understanding correctly) is that it's specific to HTML so for our use LaTeX-centric world is not so useful.

The template approach is not as complex as regexp because we could provide a well-documented template that would serve as live example (most physicists learn by example rather than studying the documentation). Additionally, in this proposal, we would preserve the template the physicist has amended, so in any moment she could have an up-to-date CV according to her desire. (her/she intending the generic physicist, not necessarily my wife :dancer:).

**Comment by tsgit** [comment]
@kaplun  pandoc can use CSL to format LaTeX bibliographies

**Comment by kaplun** [comment]
> @kaplun pandoc can use CSL to format LaTeX bibliographies

although this would be heavyweight for Legacy. I think some simple quick wins can be achieved without going full speed to CSL.

**Comment by michamos** [comment]
I did the macro thing before seeing this issue. Hopefully it is user-friendy enough. 

About the future, we were discussing with @jacquerie that we could use BibTeX as a master format for all TeX-related output, and generate the rest by running it through `bibtex` (or rather [`pybtex`](https://pybtex.org/)) with various style files.

**Comment by tsgit** [comment]
@michamos @jacquerie 

having a rich and flexible metaformat from which various output formats are generated has been discussed repeatedly. only for the latex output formats which are essentially formatted references is bibtex a good choice (and one could offer all kinds of bibstyles to format for specific journals, but isn't that like running bibtex for the users when they should know best themselves what the requirements of the target publisher are), otherwise I consider bibtex format itself an endpoint not a metaformat. It has limited \@entry types, limited set of fields, restrictions on field content, no sense of ordering, etc.

so :+1: for pursuing a common metaformat to generate a wide variety of output formats from on demand with flexible config options and parameters, but I don't think bibtex is the pivotal thing here. CSL http://citationstyles.org/ anybody?

**Comment by kaplun** [comment]
Truth is that LaTeX is today **the** format used by HEP physicists in everything they do: papers, CVs, projects etc.

BibTeX is hence perfect for them, but also our LaTeX format are of high usability for those authors that have less skill on interest in LaTeX.

HTML or text based formats are instead of little used, because they can't be really cut and paste in any useful external place. They are only nice to look at.

**Comment by tsgit** [comment]
https://github.com/inspirehep/inspire/pull/260
https://github.com/inspirehep/invenio/pull/377
https://github.com/inspirehep/invenio/pull/379
https://github.com/inspirehep/invenio/pull/380

resolve this issue
