### ISSUE TITLE
Author experiments: multiple 693__e values?

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire#215]
Currently we have some authors that have multiple 693__e values, see:

https://inspirehep.net/record/1058096/export/xm

``` xml
<datafield tag="693" ind1=" " ind2=" ">
  <subfield code="e">SLAC-PEP2-BABAR</subfield>
  <subfield code="e">CERN-ALPHA</subfield>
</datafield>
<datafield tag="693" ind1=" " ind2=" ">
  <subfield code="e">CERN-LHC-LHCB</subfield>
  <subfield code="z">Current</subfield>
</datafield>
<datafield tag="693" ind1=" " ind2=" ">
  <subfield code="e">SUPERB</subfield>
</datafield>
```

Should it be like this? Should we expect this field to have more than one entry? (maybe the author was working on more than one experiment at the same time?)

Thanks!

**Comment by david-caro** [comment]
For our own reference: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601676/events/136845158/

**Comment by annetteholtkamp** [comment]
They should just be split into 2 fields

**Comment by hoc3426** [comment]
and I've done that now for this record.

**Comment by michamos** [comment]
this is being taken care of by systematic analysis of migration failures.
