### ISSUE TITLE
BibCheck: DOI to 773

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire#224]
There are 16K documents that have a DOI but no 773 information(!)
https://inspirehep.net/search?ln=en&p=0247%3ADOI+and+not+773__p%3A**&of=hb&action_search=Search&sf=earliestdate&so=d&wl=0

An easy check can be written that populates 773 from Crossref api:
e.g.
http://api.crossref.org/works/10.1103/PhysRevD.1.1851.3

Special care has to be given to normalize journal title from the start.

**Comment by kaplun** [comment]
CC: @annetteholtkamp @michamos @tsgit

**Comment by michamos** [comment]
@annetteholtkamp wrote in https://rt.inspirehep.net/Ticket/Display.html?id=607275&results=6c7a7d808f99da55be935c34b6e05724
> Getting 773 via DOI will probably have the same problems as the current DOI import where often the journal names are not correctly generated.

**Comment by annetteholtkamp** [comment]
Indeed this causes a lot of manual curation. As long as DESY's journal workflow is not completely integrated and DOI import isn't improved I wouldn't switch on this bibcheck rule - or only for older journals. Please also keep in mind that not all our DOIs are necessarily correct. We've never done a plausibility check. So maybe we should schedule this before enabling any scripts relying on our DOIs.

- Annette


On Oct 12, 2016, at 10:53 AM, Micha Moskovic <notifications@github.com<mailto:notifications@github.com>>
 wrote:


@annetteholtkamp<https://github.com/annetteholtkamp> wrote in https://rt.inspirehep.net/Ticket/Display.html?id=607275&results=6c7a7d808f99da55be935c34b6e05724

Getting 773 via DOI will probably have the same problems as the current DOI import where often the journal names are not correctly generated.

**Comment by kaplun** [comment]
BTW @jmartinm points out the old work is here: https://github.com/pedrogaudencio/invenio/commits/bibcheck-crossref

**Comment by kaplun** [comment]
@tsgit I think Pedro's code was considering @annetteholtkamp's needs. It probably needs only testing. Could it be something you might take over?

**Comment by tsgit** [comment]
well it needs more than testing, the entire crossref api has changed and the piped query method is deprecated, code doesn't even run among other things, but it's a start with measuring and weighing variations in different fields to assign a similarity score. I see what I can do with it.

**Comment by kaplun** [comment]
When I briefly looked Pedro code is using the new JSON-based API: https://github.com/pedrogaudencio/invenio/commit/f8977f0eb39e271707cb1a80eeaa5a05e185e9f7#diff-e662df1f0ad3aec51ce036c740fab9dcR253

**Comment by kaplun** [comment]
I guess this can be closed. And in case can be an interesting project to be done again on Labs.
