### ISSUE TITLE
inexistent author page does not return 404 status

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire#249]
e.g. https://inspirehep.net/author/O.W.Kenobi.1 redirects to https://inspirehep.net/author/search?q=O.W.Kenobi.1 instead of having a 404 status.

I noticed this because a link from wikipedia to INSPIRE was broken, and wikipedia has bots monitoring broken links, which this "feature" prevents.

**Comment by tsgit** [comment]
I'd say wontfix

**Comment by jacquerie** [comment]
I like this. Can you open this on `inspire-next`, please?

**Comment by tsgit** [comment]
from a user perspective, do you rather see a `404` or a search results page with potentially useful info -- or at least an entry point for further searching ? I think the current behavior is user friendly, maybe not robot friendly. for some links Inspire distinguishes based on `User-Agent` whether to return a bad `HTTP Status` or a page

**Comment by michamos** [comment]
We could have both, like  [Github does](https://github.com/inspirehep/nonexistent), a 404 status with a search bar on the error page.

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire-next #2977](https://github.com/inspirehep/inspire-next/issues/2977) via [**ZenHub**](https://www.zenhub.com/)
