### ISSUE TITLE
CVLaTeX small improvement

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire#261]
Currently, the CVLaTeX output adds a `\bf` in front of every title. However, this doesn't correspondingly make the formulas within the title to be bolder, thus giving a lower quality result.

It is suggested to prefix formulas with: `\boldmath{}`

E.g.:
https://inspirehep.net/search?ln=en&ln=en&p=arXiv%3A1701.01871&of=tlcv

```LaTeX
{\bf ``Measurement of $\boldmath{CP}$ asymmetries in $\boldmath{D^{\pm}\rightarrow \eta^{\prime} \pi^{\pm}}$ and $\boldmath{D_s^{\pm}\rightarrow \eta^{\prime} \pi^{\pm}}$ decays''}
```

**Comment by kaplun** [comment]
cc: @tsgit

**Comment by michamos** [comment]
I would strongly suggest **not** doing this. 
Weight of symbols in math formulas can have meaning, so making everything bold could change that meaning. The standard LaTeX classes don't make formulas automatically bold for this reason.
For example,
```latex
\documentclass{article}

\begin{document}

\section{Bold text $math_{\not bold}$}
\end{document}
```
compiles to [this document](https://github.com/inspirehep/inspire/files/727219/bold_title.pdf), which uses the standard weight in the formula even though the section text has been made bold.

**Comment by michamos** [comment]
See also http://tex.stackexchange.com/questions/41379/automatically-typeset-math-in-section-headings-in-bold-face#comment84228_41379 for a similar opinion. The second most-voted reply presents an easy solution though, should we decide to implement this nonetheless, potentially in a configurable way (or can be easily copy/pasted in if @bstoraci needs it :smile:):
```latex
\makeatletter
\g@addto@macro\bfseries{\boldmath}
\makeatother
```

**Comment by tsgit** [comment]
:+1: @michamos    

wontfix and closing it.
