### ISSUE TITLE
CV LaTeX usability

### ISSUE THREAD

**Issue by tsgit** [inspirehep/inspire#265]
@michamos @kaplun 

so with all the latest improvements to CV LaTeX, there is still a usability issue. The link to INSPIRE record(s) displays generic text. 

[cvlatex.pdf](https://github.com/inspirehep/inspire/files/728157/cvlatex.pdf)

That's fine in a PDF viewer which understand links, but in printed form, this is utterly useless. How about displaying recid or doi?

`INSPIRE-HEP record/1234567`

instead?

Of course users could just leave `\showlinksfalse` whenever they want to print. Just a thought.

T.

**Comment by kaplun** [comment]
I guess this is a WONTFIX for legacy. 
CVLaTeX functionality and friends should be well thought instead on Labs.
CC: @StellaCh
