### ISSUE TITLE
don't display link to arXiv PDF if we don't have a PDF

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire#268]
Some arXiv records don't have PDFs associated, e.g. [arXiv:1502.06786](http://arxiv.org/abs/arXiv:1502.06786), but we still display a link to the PDF on the [record](https://inspirehep.net/record/1346272).

Instead, the display element should check whether we have the arXiv PDF and if not don't display the link.

**Comment by tsgit** [comment]
that's a micro-optimization

it adds substantial complexity to format generation (cpu cycles, ram, runtime cost in the legacy system)

while I agree that from an usability perspective verifying the linkability is desirable, some implementation issues need to taken into consideration. can INSPIRE maintain a list of arXiv records for which no PDF is available? are there more universal links? 

also, basing the decision on bibdocs, you must first ensure that INSPIRE has all arXiv PDF corresponding to a record and has cleaned up faulty bibdocs
sometimes there are "pdf" bibdocs which are in fact HTML pages saying there is no pdf available

T.
