### ISSUE TITLE
Add display format for HepNames awards

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire#270]
Field `678__a` is supposed to contain awards, but cataloguers are using notes for this instead right now because that field is not displayed.
When this is done, I will move through bibcheck all awards to `678__a` where they belong.

**Comment by tsgit** [comment]
@cleggm1 @hoc3426 @bing13

**Comment by hoc3426** [comment]
All the awards are in 678., e.g. https://inspirehep.net/search?cc=HepNames&p=nobel+prize&so=a&ot=667,678,680&rg=200&sf=678__a

I don't know why there are so many 667 fields with a "." - this seems to be a mistake.

**Comment by tsgit** [comment]
@hoc3426 question remains how to properly display awards. there can be multiple 678__a. do you have some mock-up or suggestion on what the display should look like? surely it shouldn't be Note: xyz prize ?

**Comment by hoc3426** [comment]
In the HEPNames mock-up we made a while ago, we had a section "Awards and Honors" https://inspirehep.net/info/HepNames/test/detailed

Doing something simple in the existing format though, we could probably just have above "note", and an entry "Awards" 
https://inspirehep.net/record/1007454
e.g.
**Awards:** Nobel Prize Physics (2004), Sakurai Prize (1986), Dirac Medal (1988)

**Comment by michamos** [comment]
@tsgit could you implement something simple as suggested by @hoc3426?

**Comment by kaplun** [comment]
Labs will have its own proper display of awards (I suppose).

**Comment by kaplun** [comment]
This is actually in the `prizes` field.

**Comment by jacquerie** [comment]
> This is actually in the prizes field.

Authors schema is not final, so that might change...

**Comment by kaplun** [comment]
At least the information is currently not lost in translation. So whatever the schema will be, at the right time you can decide how to display Prizes/Awards.
