### ISSUE TITLE
XME format should export full deleted record

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire#271]
For the migration, we want to keep the information of deleted records.

Right now, the XME format only contains minimal information (compare [XME](https://inspirehep.net/record/11/export/xme) and [bibedit](https://inspirehep.net/record/edit/#state=edit&recid=11)).
Instead, it should contain the full info of the record.

**Comment by tsgit** [comment]
but XME format is also publicly accessible and advertised, so deleted records should clearly be separate, no !?   980__a:deleted isn't obvious to external users

**Comment by michamos** [comment]
Is XME advertised? on the records detailed view, clicking on MARCXML opens the XM format, not XME.

**Comment by kaplun** [comment]
XME is advertized in the FAQ. However there are 2 different XME dumps. The one publicly accessible e.g. from the dump advertized in the FAQ or via `/export/xme`, and this already today is protecting hidden fields and can keep on avoiding exporting deleted records.

Then we are creating the full-dump via the `bibtasklet`. This can be extended to also included content from deleted records.

**Comment by jacquerie** [comment]
This is currently causing the biggest error on Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly/group/619214/.

While clearly this data is not useful for end users it's useful data for curation algorithms: for example, deleted records contain records that were determined to be duplicates. So it would be cool to have this as soon as possible.

**Comment by kaplun** [comment]
Yeah. The only issue is that this data will surely contain more outliers and crap because it won't have been curate (whoah what a tense is that) for a long time.

**Comment by jacquerie** [comment]
I've seen things you people wouldn't believe. Records with three first authors (all referring to the same guy). I watched exceptions bubble up the stack because records had two longitudes and no latitude.

Seriously, I don't expect this data to be any worse than what we've already found : )

**Comment by kaplun** [comment]
You won't believe your eyes...

**Comment by jacquerie** [comment]
\o/

ETA for a new prodsync dump with the deleted records?
