### ISSUE TITLE
What to do with records with 0 pages?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#282]
223 records say that they are 0 pages long: https://inspirehep.net/search?ln=en&p=300__a%3A%220%22. I cannot find any sensible interpretation for this, except that they are typos. What should I do with them during migration? Just discard the value of `300__a` if it's <1?

**Comment by annetteholtkamp** [comment]
Some of them seem to have negative page range, e.g.
DAE Symp.Nucl.Phys. 59 (2014) 780-779
We should fix these. We should also introduce a warning in the future - and not automatically calculate the #pages.

But most of these records are very old, and we have no fulltext. So I would just drop 300__a for them.

- Annette



On 14 Mar 2017, at 00:01, Jacopo Notarstefano <notifications@github.com<mailto:notifications@github.com>> wrote:


223 records say that they are 0 pages long: https://inspirehep.net/search?ln=en&p=300__a%3A%220%22. I cannot find any sensible interpretation for this, except that they are typos. What should I do with them during migration? Just discard the value of 300__a if it's <1?

**Comment by michamos** [comment]
> We should also introduce a warning in the future

In the schema, `number_of_pages` must be at least one, so no warning is needed, the value `0` will result in an invalid record, that is rejected.

**Comment by jacquerie** [comment]
> So I would just drop 300__a for them.

Done in https://github.com/inspirehep/inspire-next/pull/2033.
