### ISSUE TITLE
The XME format switches 961__c and 961__x

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#287]
The record creation date, according to the documentation, is found in `961__x`: https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkup

The XME format is instead putting it in `961__c`. Compare https://inspirehep.net/record/4328/export/xm and https://inspirehep.net/record/4328/export/xme.

**Comment by kaplun** [comment]
So, despite `961__` being populate on the fly by XME, it was an original field that was populate during the first big migration from SPIRES to INSPIRE.
If you check for example: https://inspirehep.net/record/885841/export/hm
```
000885841 961__ $$x2011-01-27
000885841 961__ $$c2011-02-03
```
`$x` is indeed the creation date. (and $c is a useless modification date).

Soo... XME is wrong.
