### ISSUE TITLE
Conferences: ill-formatted CNUMs

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#304]
The following records have an ill-formatted CNUM:

- [x] 1590071
- [x] 1477158
- [x] 1194030
- [x] 980162
- [x] 978008

The following record instead had an ill-formatted CNUM, which I fixed, but then I realized that maybe I shouldn't have, and decided to open this issue instead:
```
978083
```

CC: @annetteholtkamp @michamos

**Comment by michamos** [comment]
@ksachs Can you have a look at `1590071` that you added recently? I am not sure whether the starting date is correct.

**Comment by ksachs** [comment]
nothing wrong with the starting date. no idea where the wrong CNUM came from.

**Comment by michamos** [comment]
Thanks!
