### ISSUE TITLE
Journals: what's in 022__m?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#321]
This field contains some data that looks like an ISSN, but for some reason it's not in `022__a` as it should be according to the documentation: https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkupJournals.

What should we do with it during migration? This affects the following records: https://inspirehep.net/search?cc=Journals&p=022__m%3A**

**Comment by jacquerie** [comment]
CC: @annetteholtkamp @michamos

**Comment by michamos** [comment]
I moved everything to `022__a`.
