### ISSUE TITLE
Some records have empty XME

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire#332]
compare https://inspirehep.net/record/1352088/export/xm and https://inspirehep.net/record/1352088/export/xme

**Comment by jacquerie** [comment]
This Sentry error sounds relevant: https://sentry.cern.ch/inspire-sentry/inspire/group/931901/.

**Comment by kaplun** [comment]
Ouch this might indeed happen in case of crash of the format element. I'll fix it.
