### ISSUE TITLE
Sorting by 'cited by' in the search returns over 9000 results

### ISSUE THREAD

**Issue by dset0x** [inspirehep/inspire#70]
This is the simplest search that triggers returning every result in a single page:
https://inspirehep.net/search?ln=en&ln=en&p=&of=hb&action_search=Search&sf=earliestdate&so=d&rm=citation&rg=25&sc=0

Please try not to abuse this issue.

**Comment by MSusik** [comment]
Wrong title. Returns over 1000000 results.

**Comment by PXke** [comment]
It is due to Bibrank if I am right, we fixed it at TIND I think.

**Comment by kaplun** [comment]
Uh! @PXke Have you sent a patch upstream?

**Comment by PXke** [comment]
No at my knowledge, @Aurdan @blixhavn @Audub

**Comment by kaplun** [comment]
@tsgit this is still true and can bring INSPIRE to its knee. Maybe you can have a look at it?

**Comment by kaplun** [comment]
Issue moved to [inspirehep/invenio #432](https://github.com/inspirehep/invenio/issues/432) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tsgit** [comment]
commit 5490639b122b727d2df2f78f8b79415dc049d26c                                                                                             
Author: Thorsten Schwander <thorsten.schwander@gmail.com>                                                                                   
Date:   Tue Nov 22 20:10:10 2016 -0700                                                                                                       
                                                                                                                                             
    WebSearch: fix pagination when ranking                                                                                                   
                                                                                                                                              
        * sorting results by citations is properly sliced                                                                                      
          via rg and jrec                                                                                                                      
                                                                                                                                                 
    Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>

**Comment by kaplun** [comment]
Ha! Didn't remember you had fixed!
