### ISSUE TITLE
Missing space between initials in bibtex

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire#78]
From invenio-software/invenio#1011:
[...]
Author initials in the bibtex format should be separated by a space since a dot apparently is not considered as a separator in bibtex - resulting in suppression of the 2nd initial.
[...]

See:
https://inspirehep.net/record/1087430/export/hx

**Comment by tsgit** [comment]
This was fixed along with many other issues in the major bibtex format overhaul
6a7e2fbdf155173c5623eab0d5459813a67c4283

T.
